### ISSUE TITLE
"pageId is not defined" error when accessing 

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU#141]
Reproduction steps:
Visit: https://samsung.github.io/TAU/examples/mobile/UIComponents/components/list/virtuallist.html
Click any of the listed items
Observe:
Page is changed but content is not shown.
On the error console there is an error:
```
tau][6/7/2019, 9:00:23 AM] ReferenceError: pageId is not defined
    at eval (eval at <anonymous> (https://samsung.github.io/TAU/examples/mobile/UIComponents/lib/tau/mobile/js/tau.js:943:14), <anonymous>:51:3)
    at eval (<anonymous>)
    at Array.<anonymous> (https://samsung.github.io/TAU/examples/mobile/UIComponents/lib/tau/mobile/js/tau.js:943:14)
    at Object.batchCall (https://samsung.github.io/TAU/examples/mobile/UIComponents/lib/tau/mobile/js/tau.js:969:22)
    at Object.util.importEvaluateAndAppendElement (https://samsung.github.io/TAU/examples/mobile/UIComponents/lib/tau/mobile/js/tau.js:1037:10)
    at PageContainer.prototype._include (https://samsung.github.io/TAU/examples/mobile/UIComponents/lib/tau/mobile/js/tau.js:12859:18)
    at PageContainer.prototype.change (https://samsung.github.io/TAU/examples/mobile/UIComponents/lib/tau/mobile/js/tau.js:12704:28)
    at Object.routePage.open (https://samsung.github.io/TAU/examples/mobile/UIComponents/lib/tau/mobile/js/tau.js:46231:25)
    at Object.resolve (https://samsung.github.io/TAU/examples/mobile/UIComponents/lib/tau/mobile/js/tau.js:13570:13)
    at Router._loadSuccess (https://samsung.github.io/TAU/examples/mobile/UIComponents/lib/tau/mobile/js/tau.js:14239:15)
```

**Comment by TomaszLukawskiSam** [comment]
Fix has been merged.
