### ISSUE TITLE
UI Components: console errors in SwipeList example

### ISSUE THREAD

**Issue by TomaszLukawskiSam** [Samsung/TAU#52]
The app throws errors in SwipeList example

`tau.js:17436 [tau][4/26/2019, 9:08:12 AM] TypeError: Cannot read property 'getElementsByClassName' of null
    at eval (eval at <anonymous> (http://localhost:8880/examples/wearable/UIComponents/lib/tau/wearable/js/tau.js:17698:14), <anonymous>:5:22)
    at eval (eval at <anonymous> (http://localhost:8880/examples/wearable/UIComponents/lib/tau/wearable/js/tau.js:17698:14), <anonymous>:29:2)
    at eval (<anonymous>)
    at Array.<anonymous> (http://localhost:8880/examples/wearable/UIComponents/lib/tau/wearable/js/tau.js:17698:14)
    at Object.batchCall (http://localhost:8880/examples/wearable/UIComponents/lib/tau/wearable/js/tau.js:17724:22)
    at Object.util.importEvaluateAndAppendElement (http://localhost:8880/examples/wearable/UIComponents/lib/tau/wearable/js/tau.js:17792:10)
    at PageContainer.prototype._include (http://localhost:8880/examples/wearable/UIComponents/lib/tau/wearable/js/tau.js:9459:18)
    at PageContainer.prototype.change (http://localhost:8880/examples/wearable/UIComponents/lib/tau/wearable/js/tau.js:9304:28)
    at Object.routePage.open (http://localhost:8880/examples/wearable/UIComponents/lib/tau/wearable/js/tau.js:11199:25)
    at Object.resolve (http://localhost:8880/examples/wearable/UIComponents/lib/tau/wearable/js/tau.js:10169:13)`

**Comment by TomaszLukawskiSam** [comment]
Patch has already merged. The issue can be closed.

**Comment by TomaszLukawskiSam** [comment]
Issue is solved.
